import 'package:amavel_app/domain/models/alert.dart';
import 'package:amavel_app/data/repositories/alert_repository.dart';
import 'package:amavel_app/services/safety/distress_detector.dart';

/// Alert notification timing strategy
enum NotificationStrategy {
  immediate, // Send immediately (critical)
  withinHour, // Send within 1 hour (high)
  daily, // Aggregate in daily report (medium)
  weekly, // Aggregate in weekly report (low/info)
}

/// Creates alerts in Firestore and triggers notifications
class AlertDispatcher {
  final AlertRepository _repository;
  final Map<String, DateTime> _lastDispatchTimes = {};

  AlertDispatcher(this._repository);

  /// Dispatches an alert based on severity
  Future<String?> dispatchAlert(
    Alert alert, {
    DetectedDistress? distress,
  }) async {
    try {
      // Store alert in Firestore
      final alertId = await _repository.createAlert(
        userId: alert.userId,
        severity: alert.severity,
        title: alert.title,
        description: alert.description,
        detectedPatterns: alert.detectedPatterns,
        metadata: alert.metadata,
      );

      // Determine notification strategy based on severity
      final strategy = _getNotificationStrategy(alert.severity);

      // Trigger notification based on strategy
      await _triggerNotification(
        alertId,
        alert,
        strategy,
        distress,
      );

      // Log dispatch
      _lastDispatchTimes[alertId] = DateTime.now();

      return alertId;
    } catch (e) {
      print('Erro ao enviar alerta: $e');
      return null;
    }
  }

  /// Gets notification strategy for severity level
  NotificationStrategy _getNotificationStrategy(AlertSeverity severity) {
    switch (severity) {
      case AlertSeverity.critical:
        return NotificationStrategy.immediate;
      case AlertSeverity.high:
        return NotificationStrategy.withinHour;
      case AlertSeverity.medium:
        return NotificationStrategy.daily;
      case AlertSeverity.low:
        return NotificationStrategy.weekly;
    }
  }

  /// Triggers notification based on strategy
  Future<void> _triggerNotification(
    String alertId,
    Alert alert,
    NotificationStrategy strategy,
    DetectedDistress? distress,
  ) async {
    switch (strategy) {
      case NotificationStrategy.immediate:
        await _sendImmediateNotification(alert, distress);
        break;
      case NotificationStrategy.withinHour:
        await _scheduleNotification(alert, Duration(minutes: 5));
        break;
      case NotificationStrategy.daily:
        await _scheduleNotification(alert, Duration(hours: 24));
        break;
      case NotificationStrategy.weekly:
        await _scheduleNotification(alert, Duration(days: 7));
        break;
    }
  }

  /// Sends an immediate notification (critical alerts)
  Future<void> _sendImmediateNotification(
    Alert alert,
    DetectedDistress? distress,
  ) async {
    try {
      // In a production app, this would integrate with a real notification service
      // For now, we'll simulate the notification
      print('''
=== ALERTA CRÍTICO ===
Utilizador: ${alert.userId}
Título: ${alert.title}
Descrição: ${alert.description}
Padrões Detectados: ${alert.detectedPatterns}
Hora: ${DateTime.now()}
Ação Recomendada: Contacte o utilizador imediatamente
''');

      // This would trigger:
      // - Push notification to family members
      // - Email notification to caregivers
      // - SMS to emergency contacts
      // - Alert to AMAVEL monitoring dashboard
    } catch (e) {
      print('Erro ao enviar notificação imediata: $e');
    }
  }

  /// Schedules a notification for later
  Future<void> _scheduleNotification(Alert alert, Duration delay) async {
    try {
      // In production, this would use a scheduling service like Firebase Cloud Tasks
      print('Notificação agendada para ${DateTime.now().add(delay)}: ${alert.title}');

      // Simulate scheduling by recording the alert
      // In production: send to task queue or scheduled notification service
    } catch (e) {
      print('Erro ao agendar notificação: $e');
    }
  }

  /// Creates and dispatches a distress alert
  Future<String?> dispatchDistressAlert(
    String userId,
    DetectedDistress distress,
    String userInput,
  ) async {
    final severity = _mapConfidenceToSeverity(distress);
    final title = _getTitleForDistress(distress);
    final description = _getDescriptionForDistress(distress, userInput);

    final alert = Alert(
      id: '', // Will be generated by repository
      userId: userId,
      severity: severity,
      title: title,
      description: description,
      detectedPatterns: distress.matchedPatterns.join(', '),
      createdAt: DateTime.now(),
      metadata: {
        'detectionCategory': distress.detectionCategory,
        'confidence': distress.confidence,
        'userInput': userInput,
      },
    );

    return dispatchAlert(alert, distress: distress);
  }

  /// Maps distress confidence to alert severity
  AlertSeverity _mapConfidenceToSeverity(DetectedDistress distress) {
    if (distress.isCritical) {
      return AlertSeverity.critical;
    }
    if (distress.isHighSeverity && distress.confidence >= 0.8) {
      return AlertSeverity.high;
    }
    if (distress.isMediumSeverity || distress.isHighSeverity) {
      return AlertSeverity.medium;
    }
    return AlertSeverity.low;
  }

  /// Gets alert title based on distress
  String _getTitleForDistress(DetectedDistress distress) {
    switch (distress.detectionCategory) {
      case 'suicidal':
        return distress.isCritical
            ? 'Alerta Crítico: Risco Suicida'
            : 'Alerta: Sofrimento Emocional';
      case 'isolation':
        return 'Alerta: Isolamento Detectado';
      case 'health':
        return 'Alerta: Problema de Saúde Reportado';
      case 'scam':
        return 'Aviso: Possível Fraude';
      default:
        return 'Alerta de Segurança';
    }
  }

  /// Gets alert description based on distress
  String _getDescriptionForDistress(
    DetectedDistress distress,
    String userInput,
  ) {
    final patterns = distress.matchedPatterns.join(', ');
    final confidence =
        (distress.confidence * 100).toStringAsFixed(0);

    switch (distress.detectionCategory) {
      case 'suicidal':
        return distress.isCritical
            ? 'O utilizador manifestou pensamentos suicidas. Contacto imediato recomendado.'
            : 'O utilizador expressa sofrimento significativo. Considere contacto de acompanhamento.';
      case 'isolation':
        return 'O utilizador relata isolamento ou solidão. Rede de apoio pode ser necessária.';
      case 'health':
        return 'O utilizador relatou problemas de saúde. Recomenda-se contacto com profissional.';
      case 'scam':
        return 'Possível fraude ou esquema detetado. O utilizador pode estar em risco.';
      default:
        return 'Padrões detectados: $patterns (confiança: $confidence%)';
    }
  }

  /// Gets the time since last dispatch for an alert ID
  Duration? getTimeSinceLastDispatch(String alertId) {
    final lastTime = _lastDispatchTimes[alertId];
    if (lastTime == null) return null;
    return DateTime.now().difference(lastTime);
  }

  /// Checks if an alert should be rate-limited
  bool shouldRateLimit(String alertId, Duration minimumInterval) {
    final timeSince = getTimeSinceLastDispatch(alertId);
    if (timeSince == null) return false;
    return timeSince < minimumInterval;
  }

  /// Clears dispatch history for an alert
  void clearDispatchHistory(String alertId) {
    _lastDispatchTimes.remove(alertId);
  }

  /// Gets aggregated alerts for a weekly report
  Future<Map<String, dynamic>> generateWeeklyReport(String userId) async {
    try {
      final alerts = await _repository.getUserAlerts(userId);

      // Filter for alerts from past week
      final weekAgo = DateTime.now().subtract(Duration(days: 7));
      final weeklyAlerts =
          alerts.where((a) => a.createdAt.isAfter(weekAgo)).toList();

      // Group by category
      final bySeverity = <String, int>{};
      final byCategory = <String, int>{};

      for (final alert in weeklyAlerts) {
        final severity = alert.severity.toString().split('.').last;
        bySeverity[severity] = (bySeverity[severity] ?? 0) + 1;

        final category = alert.metadata['detectionCategory'] as String?;
        if (category != null) {
          byCategory[category] = (byCategory[category] ?? 0) + 1;
        }
      }

      return {
        'period': 'Semana Passada',
        'totalAlerts': weeklyAlerts.length,
        'bySeverity': bySeverity,
        'byCategory': byCategory,
        'criticalCount': bySeverity['critical'] ?? 0,
        'unresolvedCount': weeklyAlerts.where((a) => !a.isResolved).length,
      };
    } catch (e) {
      print('Erro ao gerar relatório semanal: $e');
      return {};
    }
  }
}
